language: c

git:
  deep: 1

env:
  - PYTHONUSERBASE=${HOME}/local

before_install:
  - pwd
  - echo $HOME
  - sudo apt-get install realpath
  - sudo apt-get install postgresql-server-dev-9.5
  - sudo apt-get install liblwgeom-dev
  - sudo apt-get install libproj-dev
  - sudo apt-get install python-nose python-pip python-psycopg2
  - mkdir -p ${PYTHONUSERBASE}
  - pip install --user testing.postgresql
  - dpkg -l
  - ls -l /usr/lib/liblwgeom*
  - ls -l /usr/share/postgresql/9.5/extension/postgis*.sql

install:
  - autoreconf --install
  - ./configure CFLAGS=-I/usr/include
  - make
  - ldd extension/postgis_geohash.so
  - ldd /usr/lib/postgresql/9.5/lib/postgis-*.so
  - python nosetests.py
  - make check
  - make install
  - make installcheck
