service:
  - docker

language: c

git:
  depth: 1

env:
  - PG_VERSION=9.5 POSTGIS_VERSION=2.5
  - PG_VERSION=9.5 POSTGIS_VERSION=3.0
  - PG_VERSION=10 POSTGIS_VERSION=2.5
  - PG_VERSION=10 POSTGIS_VERSION=3.0
  - PG_VERSION=11 POSTGIS_VERSION=2.5
  - PG_VERSION=11 POSTGIS_VERSION=3.0
  - PG_VERSION=12 POSTGIS_VERSION=2.5
  - PG_VERSION=12 POSTGIS_VERSION=3.0
  - PG_VERSION=13 POSTGIS_VERSION=3.0
  - PG_VERSION=13 POSTGIS_VERSION=3.1

install:
  - autoreconf --install
  - ./configure
  - make dist

script:
  - cd tests && ./install-check.sh 9.5 3.0
