service:
  - docker

language: c

git:
  depth: 1

env:
  - PYTHONUSERBASE=${HOME}/local

install:
  - autoreconf --install
  - ./configure
  - make dist

script:
  - cd tests && ./install-check.sh 9.5 3.0
