service:
  - docker

language: c

git:
  depth: 1

env:
  - POSTGIS_IMAGE=9.5-2.5
  - POSTGIS_IMAGE=9.5-3.0
  - POSTGIS_IMAGE=10-2.5
  - POSTGIS_IMAGE=10-3.0
  - POSTGIS_IMAGE=11-2.5
  - POSTGIS_IMAGE=11-3.0
  - POSTGIS_IMAGE=12-2.5
  - POSTGIS_IMAGE=12-3.0
  - POSTGIS_IMAGE=13-3.0
  - POSTGIS_IMAGE=13-3.1
  - POSTGIS_IMAGE=14-3.4 LLVM="llvm15-dev clang15"
  - POSTGIS_IMAGE=15-3.4 LLVM="llvm15-dev clang15"
  - POSTGIS_IMAGE=16-3.4 LLVM="llvm15-dev clang15"

install:
  - autoreconf --install
  - ./configure
  - make dist

script:
  - cd tests && ./install-check.sh $POSTGIS_IMAGE "$LLVM"
