language: c

git:
  deep: 1

before_install:
  - pwd
  - echo $HOME
  - sudo apt-get install realpath
  - sudo apt-get install postgresql-server-dev-9.5
  - sudo apt-get install liblwgeom-dev
  - wget -O postgis-2.3.0.tar.gz https://github.com/postgis/postgis/archive/2.3.0.tar.gz
  - tar -xzf postgis-2.3.0.tar.gz

install:
  - autoreconf --install
  - ./configure
  - make
  - make check
  - make install
  - make installcheck
