language: c

git:
  deep: 1

env:
  - PYTHONUSERBASE=${HOME}/local

install:
  - pwd
  - echo $HOME
  - sudo apt-get install realpath
  - sudo apt-get remove postgresql-*
  - sudo apt-get install postgresql-9.5 postgresql-server-dev-9.5 postgresql-9.5-postgis-2.3
  - sudo apt-get install liblwgeom-dev libproj-dev
  - sudo apt-get install python-nose python-pip python-psycopg2
  - mkdir -p ${PYTHONUSERBASE}
  - pip install --user testing.postgresql
  - autoconf --version
  - automake --version
  - autoreconf --install
  - ./configure
  - make dist
  - mkdir build
  - cd build
  - tar -xzf `find .. -name "postgis-geohash-*.tar.gz"`
  - pwd

script:
  - ./configure
  - make
  - python nosetests.py
  - make check
  - sudo make install
  - make installcheck
