service:
  - docker

language: c

git:
  depth: 1

env:
  - PG_VERSION=9.5 POSTGIS_VERSION=2.5
  - PG_VERSION=9.5 POSTGIS_VERSION=3.0

install:
  - autoreconf --install
  - ./configure
  - make dist

script:
  - cd tests && ./install-check.sh 9.5 3.0
