language: c

git:
  depth: 1

env:
  - PYTHONUSERBASE=${HOME}/local

install:
  - pwd
  - echo $HOME
  - sudo apt-get install realpath
  - sudo apt-get remove postgresql-* libproj0
  - sudo apt-get install postgresql-9.5 postgresql-server-dev-9.5 postgresql-9.5-postgis-2.3
  - sudo apt-get install liblwgeom-dev libproj-dev
  - autoconf --version
  - automake --version
  - autoreconf --install
  - export CFLAGS="-I /usr/include"
  - ./configure
  - make dist
  - tar -xzf `find -name "postgis-geohash-*.*.*.tar.gz"`
  - rm `find -name "postgis-geohash-*.*.*.tar.gz"`
  - ls -l
  - cd `find -name "postgis-geohash-*.*.*"`
  - pwd

script:
  - ./configure
  - make
  - sudo make install
  - make installcheck
