language: c

git:
  deep: 1

before_install:
  - pwd
  - echo $HOME
  - sudo apt-get install realpath
  - sudo apt-get install postgresql-server-dev-9.5
  - sudo apt-get install liblwgeom-dev
  - ls /usr
  - ls /usr/include

install:
  - autoreconf --install
  - ./configure CFLAGS=-I/usr/include
  - make
  - make check
  - make install
  - make installcheck
